name: Documentation
description: Suggest improvements or report issues in the documentation
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem with the documentation
      description: What’s wrong or confusing in the docs?
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Your suggestion
      description: How would you improve it?
