name: CI

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is running on a ${{ runner.os }} server hosted by GitHub!"
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned."
      - run: echo "Setting up JDK"

      - name: Setup
        uses: ./.github/actions/workflow_setup

      - name: Check build-logic
        run: ./gradlew check -p build-logic

      - run: echo "Run unit tests"
      - name: Test
        run: ./gradlew test

      - name: Static Analysis
        run: ./gradlew lintKotlin detektAll

      - run: echo "Assembling main outputs"
      - name: Assemble
        run: ./gradlew assemble
      - run: echo "Build status report=${{ job.status }}."

      - run: echo "Uploading build artifacts"
      - name: Upload a Build Artifact (APK)
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk